import { execFileSync } from "node:child_process";
import { expect, test, type APIRequestContext, type Page } from "@playwright/test";

/**
 * EV-201 — the two sentences whose witness is the TRAINEE's own data, against a real
 * b-fit-api and a real Postgres.
 *
 * `qa/coach-affordance.spec.ts` drives AC1, AC2, AC3 and the browser half of AC4 in
 * fixture mode. It cannot drive these two, and neither can any fixture:
 *
 *   · **AC4** — *"Nothing reaches the trainee until you confirm."* Read from the
 *     trainee's own `GET /me/plan`, before and after the coach presses Publish. See the
 *     test's own comment for the half that is NOT constructible against a live api
 *     today, and why.
 *   · **AC5** — *"…doesn't use {FirstName}'s daily regenerations."* The counter is
 *     `weekly_meal_plan.regen_count` / `regen_date` on the TRAINEE's plan row and no
 *     endpoint serves it, so it is read straight out of Postgres before and after a
 *     swap driven through the portal's own UI.
 *
 * ⚠️ **Cost.** Nothing here may reach a paid model. The api under test must run with
 * `BFIT_AI_ENABLED=false`, which is the default: the meal week is generated by the
 * deterministic stub (`source: "STUB"`, asserted below) and swap candidates come from
 * the same stub through `planned_meal.swap_candidates`. This spec never calls
 * `refreshSwapOptions`, `POST /coach-portal/clients/{id}/nutrition/week/apply` or any
 * regeneration.
 *
 * Prerequisites — the live config does NOT provision these:
 *
 *   docker run -d --name bfit-pg-ev201 -p 55433:5432 \
 *     -e POSTGRES_USER=bfit -e POSTGRES_PASSWORD=bfit -e POSTGRES_DB=bfit postgres:15
 *   # EXERCISE_PROVIDER=seed: a throwaway database has only the 279 V21/V22 `seed` rows
 *   # and `CatalogAvailabilityService.hasRows()` counts the ACTIVE provider's rows only,
 *   # so the default `musclewiki` makes every catalog read a 503 (BUG-057's rule).
 *   cd b-fit-api && BFIT_AI_ENABLED=false EXERCISE_PROVIDER=seed SPRING_PROFILES_ACTIVE=local \
 *     JWT_SECRET=… OTP_PEPPER=… MFA_ENC_KEY="$(openssl rand -base64 32)" \
 *     ./gradlew bootRun --args='--server.port=8099 \
 *       --spring.datasource.url=jdbc:postgresql://localhost:55433/bfit'
 *   npx playwright test --config playwright.live.config.ts qa/coach-affordance.live.spec.ts
 *
 * The coach must hold NO active link when the run starts; the spec revokes what it
 * creates, so it is re-runnable.
 */

const API_ORIGIN = process.env.COACH_LIVE_API_ORIGIN || "http://localhost:8099";
/** The container the throwaway Postgres runs in — the counter has no endpoint. */
const PG_CONTAINER = process.env.COACH_LIVE_PG_CONTAINER || "bfit-pg-ev201";

const COACH = { email: "coach@evoli.fit", password: "Password123!" };
const TRAINEE = { email: "user@evoli.fit", password: "Password123!" };
const TRAINEE_NAME = "Test User";

const PUBLISH_HINT =
  "Publish shows you the safety changes first. Nothing reaches the trainee until you confirm.";
const SWAP_FREE = `Swapping a meal doesn't use ${TRAINEE_NAME}'s daily regenerations.`;
const REGENERATE_LIMIT = `Day regenerations share ${TRAINEE_NAME}'s daily limit.`;

test.describe.configure({ mode: "serial" });

async function bearer(request: APIRequestContext, who: { email: string; password: string }) {
  const res = await request.post(`${API_ORIGIN}/auth/login`, { data: who });
  expect(res.status(), "the seeded account must log in").toBe(200);
  const body = (await res.json()) as { accessToken?: string };
  expect(body.accessToken, "login must return an access token (no MFA on the seed)").toBeTruthy();
  return body.accessToken!;
}

async function signIn(page: Page) {
  await page.goto("/login");
  await page.getByLabel("Email").fill(COACH.email);
  await page.getByLabel("Password").fill(COACH.password);
  await page.getByRole("button", { name: "Sign in" }).click();
  await page.waitForURL("/");
}

/** The trainee's day-regeneration counter, straight off their plan row. */
function regenCounter(): string {
  return execFileSync(
    "docker",
    [
      "exec",
      PG_CONTAINER,
      "psql",
      "-U",
      "bfit",
      "-d",
      "bfit",
      "-tAc",
      `select w.regen_count || '/' || coalesce(w.regen_date::text, 'no-date')
         from weekly_meal_plan w join users u on u.id = w.user_id
        where u.email = '${TRAINEE.email}' and w.status = 'ACTIVE'
        order by w.week_start_date desc limit 1`,
    ],
    { encoding: "utf8" }
  ).trim();
}

/**
 * Link the seeded coach and trainee exactly as the app does, and return the client url.
 *
 * Idempotent on purpose: an earlier failed run leaves an ACTIVE link behind, and a spec
 * that can only run against a virgin database is a spec nobody re-runs.
 */
async function link(page: Page, request: APIRequestContext): Promise<string> {
  // The roster is a server render; wait for the capacity meter before deciding whether
  // the trainee is on it, or `isVisible()` answers "no" about a page that has not drawn.
  await expect(page.getByText(/profiles · /)).toBeVisible();
  const existing = page.getByRole("link", { name: TRAINEE_NAME }).first();
  if (await existing.isVisible()) {
    await existing.click();
    await page.waitForURL(/\/clients\/[0-9a-f-]{36}$/);
    return page.url();
  }
  await page.getByRole("button", { name: "Invite a trainee" }).click();
  const url = await page.getByLabel("Invite link").inputValue();
  const token = new URL(url).pathname.split("/i/")[1];

  const traineeToken = await bearer(request, TRAINEE);
  const accept = await request.post(`${API_ORIGIN}/me/my-coach/accept`, {
    headers: { Authorization: `Bearer ${traineeToken}` },
    data: { token, privacyPolicyVersion: "v1.0" },
  });
  expect(accept.status(), await accept.text()).toBe(200);

  await page.goto("/");
  await page.getByRole("link", { name: TRAINEE_NAME }).first().click();
  await page.waitForURL(/\/clients\/[0-9a-f-]{36}$/);
  return page.url();
}

async function revoke(page: Page, clientUrl: string) {
  await page.goto(clientUrl);
  await page.getByRole("button", { name: "More" }).click();
  await page.getByRole("menuitem", { name: "Revoke access" }).click();
  await page.getByRole("button", { name: "Revoke access", exact: true }).last().click();
  await page.waitForURL("/");
}

/**
 * AC4, in the only half a live run can witness TODAY.
 *
 * ⛔ The routine WRITE path is a registered contract deviation (`src/lib/coachApi.ts`,
 * "KNOWN BROKEN AGAINST LIVE", and `qa/contract-deviations.ts`): the api's
 * `PUT …/routine/draft` takes the whole `@Valid Routine` document and this surface
 * sends `{name, trainingDays}`, so a live "Save draft" — and therefore the SAVE half of
 * `previewPublishAction` — answers 400 before any preview opens. That is pre-existing
 * and untouched by EV-201.
 *
 * So the positive control ("confirming DOES reach the trainee") is not constructible
 * against a real api yet, and this test does not pretend otherwise: it asserts the
 * claim's load-bearing half — that pressing **Publish** moves nothing in the trainee's
 * own `GET /me/plan`. The other half is driven in fixture mode, where the write path
 * works: `qa/coach-affordance.spec.ts` (nothing publishes on the preview) and, on main,
 * `qa/coach-routine.spec.ts` "Publish with these changes ships the repaired plan".
 *
 * When the write path lands, the positive control belongs here.
 */
test("AC4 — pressing Publish moves nothing in the trainee's own plan", async ({
  page,
  request,
}) => {
  test.slow();
  await signIn(page);
  const clientUrl = await link(page, request);
  const traineeToken = await bearer(request, TRAINEE);
  const asTrainee = { Authorization: `Bearer ${traineeToken}` };

  const planSeen = async () => {
    const res = await request.get(`${API_ORIGIN}/me/plan`, { headers: asTrainee });
    if (res.status() === 404) return "no plan";
    expect(res.status(), await res.text()).toBe(200);
    return `plan: ${(await res.json()).name as string}`;
  };
  const before = await planSeen();

  await page.goto(`${clientUrl}/routine`);
  const build = page.getByRole("button", { name: "Build a plan" });
  if (await build.isVisible()) await build.click();

  // EV-201 AC4's line is on the screen before Publish is ever pressed.
  await expect(page.getByText(PUBLISH_HINT)).toBeVisible();

  // One exercise per day. A result row is the only button in the picker carrying a
  // `title` (the full exercise name); "Done" and the close control do not.
  for (const nth of [0, 1]) {
    await page.getByRole("button", { name: "Add exercise" }).nth(nth).click();
    const picker = page.getByRole("dialog");
    await picker.getByLabel("Search the catalog").fill(nth === 0 ? "Squat" : "Bench");
    await picker.locator("button[title]").first().click();
    await expect(picker.getByText(/^Added /)).toBeVisible();
    await picker.getByRole("button", { name: "Done" }).click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
  }

  await page.getByRole("button", { name: "Publish", exact: true }).first().click();
  // Whatever the api answers, the coach has not confirmed anything — so the trainee's
  // app, read at this moment, shows exactly what it showed before.
  await expect(page.getByRole("button", { name: "Publish", exact: true }).first()).toBeEnabled();
  expect(await planSeen(), `the trainee's plan must not move (before=${before})`).toBe(before);

  await revoke(page, clientUrl);
});

test("AC5 — a swap leaves the trainee's day-regeneration counter where it was", async ({
  page,
  request,
}) => {
  test.slow();
  const traineeToken = await bearer(request, TRAINEE);
  const asTrainee = { Authorization: `Bearer ${traineeToken}` };

  // A current-week plan, generated by the trainee's own endpoint. `source: "STUB"` is
  // asserted, not assumed: it is this spec's proof that no paid model was called.
  let week = await request.get(`${API_ORIGIN}/me/nutrition/plan/week`, { headers: asTrainee });
  if (week.status() === 404) {
    const generated = await request.post(`${API_ORIGIN}/me/nutrition/plan/week`, {
      headers: asTrainee,
      data: {},
    });
    expect(generated.status(), await generated.text()).toBe(200);
  }
  await expect
    .poll(
      async () => {
        week = await request.get(`${API_ORIGIN}/me/nutrition/plan/week`, { headers: asTrainee });
        return (await week.json()).status as string;
      },
      { timeout: 120_000, message: "the stub week must finish generating" }
    )
    .toBe("ACTIVE");
  const weekBody = await week.json();
  expect(weekBody.source, "no paid model may be reached by this run").toBe("STUB");

  await signIn(page);
  const clientUrl = await link(page, request);
  await page.goto(`${clientUrl}/nutrition`);

  // AC5: the new line and the untouched regeneration line, both, in the same region.
  await expect(page.getByText(REGENERATE_LIMIT, { exact: true })).toBeVisible();
  await expect(page.getByText(SWAP_FREE, { exact: true })).toBeVisible();

  const counterBefore = regenCounter();

  const swapButton = page.getByRole("button", { name: /^Swap meal: / }).first();
  const swapped = (await swapButton.getAttribute("aria-label"))!.replace("Swap meal: ", "");
  await swapButton.click();
  const dialog = page.getByRole("dialog");
  await expect(dialog).toBeVisible();
  // A meal with no cached alternatives proves nothing either way — fail loudly instead.
  await expect(dialog.getByText("No swap options are available for this meal.")).toHaveCount(0);
  // A candidate row is the only button in this dialog carrying a `title` — the modal's
  // own "Close" control does not, and clicking that proves nothing.
  const candidate = dialog.locator("button[title]").first();
  await expect(candidate).toBeVisible();
  const chosen = (await candidate.innerText()).split("\n")[0];
  await candidate.click();

  // The swap completed: the modal closed and the meal on the page is the new one.
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(page.getByText(chosen).first()).toBeVisible();
  expect(chosen, "the swap must actually change the meal").not.toBe(swapped);

  const counterAfter = regenCounter();
  // Printed, not just compared: AC5 asks QA to STATE both values, and a spec that only
  // asserts equality leaves the run with no record of what they were.
  // eslint-disable-next-line no-console
  console.log(
    `EV-201 AC5 — regen_count/regen_date  before=${counterBefore}  after=${counterAfter}` +
      `  (swapped "${swapped}" → "${chosen}")`
  );
  expect(
    counterAfter,
    `regen_count/regen_date before=${counterBefore} after=${counterAfter}`
  ).toBe(counterBefore);

  await revoke(page, clientUrl);
});
